[package]
name = "bip39"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39-upstream = { package = "bip39", version = "2.0", features = ["all-languages"] }
thiserror = "1.0"
rand = "0.8"

[dev-dependencies]
hex = "0.4"
criterion = "0.5"

[[bench]]
name = "benchmarks"
harness = false
